### ISSUE TITLE
chisel does not work with swift

### ISSUE THREAD

**Issue by cuong1112035** [facebook/chisel#148]
I try chisel but it only work with objective-c project. when trying with swift project I got some error like this 
border self.view
error: error: use of undeclared identifier 'self'
error: 1 errors parsing expression
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 79, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.4.0/libexec/commands/FBDisplayCommands.py", line 75, in run
    if viewHelpers.isView(obj):
  File "/usr/local/opt/chisel/libexec/fblldbviewhelpers.py", line 66, in isView
    return isUIView(obj) or isNSView(obj)
  File "/usr/local/opt/chisel/libexec/fblldbviewhelpers.py", line 60, in isUIView
    return not runtimeHelpers.isMacintoshArch() and fb.evaluateBooleanExpression('[(id)%s isKindOfClass:(Class)[UIView class]]' % obj)
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 70, in evaluateBooleanExpression
    return (int(evaluateIntegerExpression('(BOOL)(' + expression + ')', printErrors)) != 0)
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 62, in evaluateIntegerExpression
    output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
AttributeError: 'NoneType' object has no attribute 'replace'

Could you give me some advice to make it run with swift?

**Comment by alanzeino** [comment]
There are some specific swift commands. Type `help` into LLDB and you'll see them:

```
  poobjc       -- For more information run 'help poobjc'
  poswift      -- For more information run 'help poswift'
```

**Comment by kastiglione** [comment]
@cuong1112035 in #121 support was added to ensure chisel evaluates code correctly regardless of whether code is objc or swift. If you have any troubles, please let us know, thanks.

**Comment by srpoucse** [comment]
I see the same issue, any suggestions?

**Comment by jotshin** [comment]
I'm having the same issue while using `border`. However there's no problem for `show/hide` the same view.

error: error: <EXPR>:1:11: error: use of undeclared type '$__lldb_context'
extension $__lldb_context {                            
          ^~~~~~~~~~~~~~~

error: <EXPR>:18:5: error: use of unresolved identifier '$__lldb_injected_self'
    $__lldb_injected_self.$__lldb_wrapped_expr_11(     
    ^~~~~~~~~~~~~~~~~~~~~

error: error: use of undeclared identifier 'None'
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.5.0/libexec/commands/FBDisplayCommands.py", line 78, in run
    if viewHelpers.isView(obj):
  File "/usr/local/opt/chisel/libexec/fblldbviewhelpers.py", line 66, in isView
    return isUIView(obj) or isNSView(obj)
  File "/usr/local/opt/chisel/libexec/fblldbviewhelpers.py", line 60, in isUIView
    return not runtimeHelpers.isMacintoshArch() and fb.evaluateBooleanExpression('[(id)%s isKindOfClass:(Class)[UIView class]]' % obj)
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 84, in evaluateBooleanExpression
    return (int(evaluateIntegerExpression('(BOOL)(' + expression + ')', printErrors)) != 0)
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 76, in evaluateIntegerExpression
    output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by kastiglione** [comment]
Thanks for the reports. I'll try to figure out the root cause.
