### ISSUE TITLE
pactions report error when argument has no action and target

### ISSUE THREAD

**Issue by StYaphet** [facebook/chisel#203]
Error message are:
error: error: Execution was interrupted, reason: Attempted to dereference an invalid ObjC Object or send it an unrecognized selector.
The process has been returned to the state before expression evaluation.
error: error: use of undeclared identifier 'None'
Traceback (most recent call last):
  File "/usr/local/Cellar/chisel/1.5.0/libexec/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.5.0/libexec/commands/FBPrintCommands.py", line 449, in run
    targetCount = fb.evaluateIntegerExpression('[{targets} count]'.format(targets=targets))
  File "/usr/local/Cellar/chisel/1.5.0/libexec/fblldbbase.py", line 76, in evaluateIntegerExpression
    output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by kastiglione** [comment]
Thanks!

**Comment by kastiglione** [comment]
I just tried, but couldn't reproduce the problem. For a UIButton with no actions, it doesn't print out anything. I should change this to print "no actions".

> Execution was interrupted, reason: Attempted to dereference an invalid ObjC Object or send it an unrecognized selector.

This raises a question: what is the class of the argument you passed to `pactions`?

**Comment by StYaphet** [comment]
Oh, it's my fault, I pass a instance of UIImageView class. 囧
It's very nice for you adding some message show on the debug console, thank you very much.
