### ISSUE TITLE
visualize in Swift Error

### ISSUE THREAD

**Issue by ydms** [facebook/chisel#222]
xcode 9, Swift4
in oc ok!

```
visualize self.view

error: error: use of undeclared identifier 'self'
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.7.1/libexec/commands/FBVisualizationCommands.py", line 178, in run
    _visualize(arguments[0])
  File "/usr/local/Cellar/chisel/1.7.1/libexec/commands/FBVisualizationCommands.py", line 146, in _visualize
    if fb.evaluateBooleanExpression('(unsigned long)CFGetTypeID((CFTypeRef)' + target + ') == (unsigned long)CGImageGetTypeID()'):
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

```
visualize `self.view`

error: error: use of undeclared identifier 'self'
```

```
visualize 0x7faf6b566d50

error: error: use of undeclared identifier 'CGFloat'
error: use of undeclared identifier 'CGRect'
error: missing '[' at start of message send expression
error: expected ']'
to match this '['
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.7.1/libexec/commands/FBVisualizationCommands.py", line 178, in run
    _visualize(arguments[0])
  File "/usr/local/Cellar/chisel/1.7.1/libexec/commands/FBVisualizationCommands.py", line 152, in _visualize
    _showLayer('[(id)' + target + ' layer]')
  File "/usr/local/Cellar/chisel/1.7.1/libexec/commands/FBVisualizationCommands.py", line 103, in _showLayer
    width = float(fb.evaluateExpression('(CGFloat)(' + size + '.width)'))
TypeError: float() argument must be a string or a number
```

**Comment by ollieatkinson** [comment]
Also seeing the same issue, tested on older version 1.5.0 with the same result:

```lldb
(lldb) visualize titleView
error: error: use of undeclared identifier 'CGFloat'
error: use of undeclared identifier 'CGRect'
error: missing '[' at start of message send expression
error: expected ']'
to match this '['
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.7.1/libexec/commands/FBVisualizationCommands.py", line 178, in run
    _visualize(arguments[0])
  File "/usr/local/Cellar/chisel/1.7.1/libexec/commands/FBVisualizationCommands.py", line 152, in _visualize
    _showLayer('[(id)' + target + ' layer]')
  File "/usr/local/Cellar/chisel/1.7.1/libexec/commands/FBVisualizationCommands.py", line 103, in _showLayer
    width = float(fb.evaluateExpression('(CGFloat)(' + size + '.width)'))
TypeError: float() argument must be a string or a number
```

**Comment by kastiglione** [comment]
The issue with `visualize` should be resolved by #232.

**Comment by kastiglione** [comment]
The "undeclared identifier 'self'" bug should be resolved by #171.
