### ISSUE TITLE
pcurl error: error: use of undeclared identifier 'None'

### ISSUE THREAD

**Issue by klische** [facebook/chisel#252]
Just installed chisel.
`command script import /usr/local/opt/chisel/libexec/fblldb.py` in ~/.lldbinit
Also ran the above in the console while debbuging, printed no errors. However, when I try this command:
`pcurl urlRequest` (a Swift URLRequest). I get the following in the console:

> (lldb) pcurl urlRequest
error: error: use of undeclared identifier 'None'
error: error: use of undeclared identifier 'None'
error: error: use of undeclared identifier 'None'
error: error: use of undeclared identifier 'None'
error: error: use of undeclared identifier 'None'
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 84, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.8.1/libexec/commands/FBPrintCommands.py", line 550, in run
    HTTPHeadersCount = fb.evaluateIntegerExpression('[{} count]'.format(HTTPHeaders))
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 108, in evaluateIntegerExpression
    output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by vivandro** [comment]
Were you able to resolve this issue? I'm seeing similar error as well. Here;s my console output for `pviews`.

<img width="787" alt="screen shot 2019-02-12 at 6 06 23 pm" src="https://user-images.githubusercontent.com/686545/52738998-ce02f680-2f84-11e9-99d2-1e2b66279697.png">

**Comment by klische** [comment]
No, I was not able to resolve this issue. I gave up on it and removed Chisel from my project :(
