### ISSUE TITLE
pviews   AttributeError: 'NoneType' object has no attribute 'split' ? 

### ISSUE THREAD

**Issue by Ambtion** [facebook/chisel#276]
border view
Traceback (most recent call last):
  File "/usr/local/Cellar/chisel/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/commands/FBDisplayCommands.py", line 78, in run
    for view, level in viewHelpers.subviewsOfView(obj):
  File "/usr/local/Cellar/chisel/fblldbviewhelpers.py", line 75, in subviewsOfView
    for i in xrange(subviewsCount):
NameError: name 'xrange' is not defined

**Comment by Ambtion** [comment]
I chang xrange to  range in  fblldbviewhelpers.py; it done
