### ISSUE TITLE
Xcode 12.3 NameError: name 'lldb' is not defined

### ISSUE THREAD

**Issue by yanyi0** [facebook/chisel#295]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
error: module importing failed: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/opt/chisel/libexec/fbchisellldb.py", line 12, in <module>
    import lldb
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python3/lldb/__init__.py", line 101, in <module>
    import six
ModuleNotFoundError: No module named 'six'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
error: module importing failed: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/LLDB/lldb_commands/dslldb.py", line 23, in <module>
    import lldb
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python3/lldb/__init__.py", line 101, in <module>
    import six
ModuleNotFoundError: No module named 'six'

**Comment by a919312** [comment]
Do u finish this problem?
