### ISSUE TITLE
Many OS X features say that work break in OS X apps  

### ISSUE THREAD

**Issue by DerekSelander** [facebook/chisel#91]
Try testing this on an OS X application on a particular NSView you know the visual location of.

This is after the latest version of Chisel is loaded into LLDB

```lldb
pro at -n Xcode 
hide 0x7fe500fd5660
```
The above works. But try the mask command
``` lldb
mask 0x7fe500fd5660
error: error: use of undeclared identifier 'UIWindow'
error: expected expression
error: use of undeclared identifier 'UIApplication'
error: expected ']'
note: to match this '['
error: 4 errors parsing expression
error: error: use of undeclared identifier 'UIView'
error: expected expression
error: use of undeclared identifier 'None'
error: expected ']'
note: to match this '['
error: 4 errors parsing expression
error: use of undeclared identifier 'None'
error: 1 errors parsing expression
error: error: use of undeclared identifier 'UIWindow'
error: expected expression
error: use of undeclared identifier 'UIApplication'
error: expected ']'
note: to match this '['
error: 4 errors parsing expression
error: error: use of undeclared identifier 'None'
error: 1 errors parsing expression
Traceback (most recent call last):
  File "/Users/derekselander/lldb/fblldb.py", line 81, in runCommand
    command.run(args, options)
  File "/Users/derekselander/lldb/commands/FBDisplayCommands.py", line 93, in run
    viewHelpers.maskView(viewOrLayer, options.color, options.alpha)
  File "/Users/derekselander/lldb/fblldbviewhelpers.py", line 24, in maskView
    origin = convertPoint(0, 0, viewOrLayer, window)
  File "/Users/derekselander/lldb/fblldbviewhelpers.py", line 47, in convertPoint
```

The border command that says is available in the README also doesn't work on OS X
``` lldb
border 0x7fe500fd5660
error: use of undeclared identifier 'UIColor'
error: 1 errors parsing expression
```

Seems like some of these commands are hardcoded for iOS only?

**Comment by kastiglione** [comment]
@DerekSelander Thanks for the report! Chisel doesn't have a test suite (it would be great to add one: #15) and the majority of contributors and maintainers use chisel with iOS. I'd be more than happy to accept pull requests if you were interested in contributing :ski

**Comment by kastiglione** [comment]
_Reopened following accidental close…_

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kastiglione** [comment]
@DerekSelander Feel free to re-open and we can discuss any OS X issues further.
